version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../config/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - web
    depends_on:
      - backend
      - frontend

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-securepassword}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-app}
    volumes:
      - ../data/mongodb:/data/db
    networks:
      - backend

  backend:
    image: ${IMAGE_PATH}/backend:latest
    container_name: backend
    restart: unless-stopped
    environment:
      # Server Configuration
      - NODE_ENV=production
      - PORT=3000
      
      # Database Configuration
      - MONGODB_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-securepassword}@mongodb:27017/${MONGO_DATABASE:-app}?authSource=admin
      
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      
      # Email Configuration
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      
      # API URLs
      - API_URL=http://${DOMAIN}/api
      - FRONTEND_URL=http://${DOMAIN}
      
      # Discord Notifications
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    depends_on:
      - mongodb
    networks:
      - web
      - backend

  frontend:
    image: ${IMAGE_PATH}/frontend:latest
    container_name: frontend
    restart: unless-stopped
    environment:
      # API Configuration
      - VITE_API_URL=http://${DOMAIN}/api
      - VITE_PUBLIC_URL=http://${DOMAIN}
      - VITE_APP_NAME=${APP_NAME:-Task Manager}
    depends_on:
      - backend
    networks:
      - web

networks:
  web:
    name: web
    external: false
  backend:
    name: backend
    external: false
